# Generated by Django 5.2.7 on 2025-10-03 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sale_date', models.DateTimeField(verbose_name='Дата продажи')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Электронная почта клиента')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
